# Generated by Django 3.0.4 on 2020-03-14 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('plot', models.CharField(max_length=500)),
                ('Director', models.CharField(max_length=50)),
                ('writter', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=550)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
